//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.21 at 05:40:23 PM PST 
//


package hello;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Items", propOrder = {
    "item"
})
public class Items {

    protected List<Items.Item> item;

  
    public List<Items.Item> getItem() {
        if (item == null) {
            item = new ArrayList<Items.Item>();
        }
        return this.item;
    }



    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productName",
        "quantity",
        "usPrice",
        "comment",
        "shipDate"
    })
    public static class Item {

        @XmlElement(required = true)
        protected String productName;
        protected int quantity;
        @XmlElement(name = "USPrice", required = true)
        protected BigDecimal usPrice;
        protected String comment;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar shipDate;
        @XmlAttribute(name = "partNum", required = true)
        protected String partNum;

        public String getProductName() {
            return productName;
        }


        public void setProductName(String value) {
            this.productName = value;
        }

        public int getQuantity() {
            return quantity;
        }

   
        public void setQuantity(int value) {
            this.quantity = value;
        }

        public BigDecimal getUSPrice() {
            return usPrice;
        }

        public void setUSPrice(BigDecimal value) {
            this.usPrice = value;
        }


        public String getComment() {
            return comment;
        }

        public void setComment(String value) {
            this.comment = value;
        }

        public XMLGregorianCalendar getShipDate() {
            return shipDate;
        }


        public void setShipDate(XMLGregorianCalendar value) {
            this.shipDate = value;
        }


        public String getPartNum() {
            return partNum;
        }

        public void setPartNum(String value) {
            this.partNum = value;
        }

    }

}
